import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Fireworks from '@fireworks-js/react'
import { url } from 'inspector'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [year, setYear] = useState(new Date().getUTCFullYear())
  const newYear = new Date(`Jan 2, ${year}`).getTime()

  const [days, setDays] = useState(0)
  const [hours, setHours] = useState(0)
  const [minutes, setMinutes] = useState(0)
  const [seconds, setSeconds] = useState(0)

  useEffect(() => {
    const countdown = () => {
      const now = new Date().getTime()
      const distance = newYear - now
      
      const da = Math.floor(distance / (1000 * 60 * 60 * 24))
      const ho = Math.floor(distance / (1000 * 60 * 60) % 24)
      const mi = Math.floor((distance / (1000 * 60)) % 60)
      const se = Math.floor((distance / 1000) % 60)

      setDays(da)
      setHours(ho)
      setMinutes(mi)
      setSeconds(se)

      if(distance < 0) {
        clearInterval(countdownInterval)
        setYear(year + 1)
      }
    }

    const countdownInterval = setInterval(countdown, 1000)
  }, [newYear])

  return (
    <>
      <Head>
        <title>Year Countdow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <p className={styles.header}>Countdown to new year</p>
          <h1 className={styles.year}>{ year }</h1>
          <div className={styles.timer}>
            <div className={styles["timer-box"]}>
              <div className={styles["timer-box__count"]}>
                <span id={styles.days}>{ days }</span>
              </div>
              <div className={styles["timer-box__text"]}>Days</div>
            </div>
            <div className={styles["timer-box"]}>
              <div className={styles["timer-box__count"]}>
                <span id='hours'>{ hours }</span>
              </div>
              <div className={styles["timer-box__text"]}>Hours</div>
            </div>
            <div className={styles["timer-box"]}>
              <div className={styles["timer-box__count"]}>
                <span id='minutes'>{ minutes }</span>
              </div>
              <div className={styles["timer-box__text"]}>Minutes</div>
            </div>
            <div className={styles["timer-box"]}>
              <div className={styles["timer-box__count"]}>
                <span id='seconds'>{ seconds }</span>
              </div>
              <div className={styles["timer-box__text"]}>Seconds</div>
            </div>
          </div>
        </div>
        <div className={styles['firewords-container']}>
          <Fireworks
            options={{
              rocketsPoint: {
                min: 0,
                max: 100
              }
            }}
            style={{
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              position: 'fixed',
            }}
          />
        </div>
      </main>
    </>
  )
}
